services:
  docs:
    image: crazy88_quotes_local_docs
    container_name: crazy88_quotes_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./crazy88_quotes:/app/crazy88_quotes:z
    ports:
      - '9000:9000'
    command: /start-docs
